// Auto-generated by tools/package_arduino.py — do not edit manually.
//
// Selects the correct port implementation for the target Arduino architecture.
// Architecture macros are defined by the Arduino core:
//   ARDUINO_ARCH_AVR    — ATmega328P, ATmega2560, etc. (Uno, Nano, Mega)
//
// To add a new architecture:
//   1. Add the port implementation as port_<arch>.inc in this directory.
//   2. Add an #elif branch below.

#if defined(ARDUINO_ARCH_AVR)
#  include "port_avr.inc"
#else
#  error "QuartzRTOS: unsupported Arduino architecture. \
Supported: AVR (Uno/Nano/Mega). \
See https://github.com/mseminatore/quartz for more information."
#endif
