#!/usr/bin/env python3
"""
package_arduino.py — Assembles the extras/arduino/src/ directory from the
main Quartz RTOS source tree.

Run this script from the repository root before a release:
    python3 tools/package_arduino.py

What it does
------------
1. Copies all kernel .c sources from src/ into extras/arduino/src/, rewriting
   relative include paths (../../include/ and ../include/ → flat).
2. Copies all internal kernel headers (src/*.h) into extras/arduino/src/.
3. Copies all public headers (include/*.h) into extras/arduino/src/.
4. Copies the AVR port (port/avr_atmega/port.c) as port_avr.inc so that
   Arduino's build system does not attempt to compile it directly on
   non-AVR targets (only .c/.cpp files are compiled; .inc files are not).
5. Generates extras/arduino/src/port.c — a dispatch file that #includes
   the correct architecture-specific implementation.
6. Copies LICENSE to extras/arduino/.

The script is idempotent; re-running it will overwrite any previously
generated files.
"""

import argparse
import os
import re
import shutil
import sys
import zipfile

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ARDUINO_SRC = os.path.join(REPO_ROOT, "extras", "arduino", "src")
ARDUINO_ROOT = os.path.join(REPO_ROOT, "extras", "arduino")

# Kernel .c sources to copy
KERNEL_SOURCES = [
    "src/list.c",
    "src/task.c",
    "src/sem.c",
    "src/mutex.c",
    "src/queue.c",
    "src/timer.c",
]

# Internal headers to copy
INTERNAL_HEADERS = [
    "src/port.h",
    "src/list.h",
    "src/compat.h",
    "src/kmem.h",
]

# Public headers to copy
PUBLIC_HEADERS = [
    "include/rtos.h",
    "include/rtos_config.h",
    "include/rtos_task.h",
    "include/rtos_sem.h",
    "include/rtos_mutex.h",
    "include/rtos_queue.h",
    "include/rtos_timer.h",
    "include/rtos_trace.h",
    "include/rtos_trace_chrome.h",
]

# Port source files to copy as .inc (prevents Arduino from auto-compiling them)
PORT_INC_FILES = {
    "port/avr_atmega/port.c": "port_avr.inc",
}

# Dispatch port.c content
PORT_C_CONTENT = """\
// Auto-generated by tools/package_arduino.py — do not edit manually.
//
// Selects the correct port implementation for the target Arduino architecture.
// Architecture macros are defined by the Arduino core:
//   ARDUINO_ARCH_AVR    — ATmega328P, ATmega2560, etc. (Uno, Nano, Mega)
//
// To add a new architecture:
//   1. Add the port implementation as port_<arch>.inc in this directory.
//   2. Add an #elif branch below.

#if defined(ARDUINO_ARCH_AVR)
#  include "port_avr.inc"
#else
#  error "QuartzRTOS: unsupported Arduino architecture. \\
Supported: AVR (Uno/Nano/Mega). \\
See https://github.com/mseminatore/quartz for more information."
#endif
"""

# Patterns to rewrite in copied .c / .h files
# Maps regex pattern → replacement.  Applied in order.
INCLUDE_REWRITES = [
    # e.g.  "../include/rtos_task.h"  → "rtos_task.h"
    (r'#include\s+"\.\.\/\.\.\/include\/([^"]+)"', r'#include "\1"'),
    (r'#include\s+"\.\.\/include\/([^"]+)"',       r'#include "\1"'),
    # e.g.  "../../src/port.h"  → "port.h"
    (r'#include\s+"\.\.\/\.\.\/src\/([^"]+)"',     r'#include "\1"'),
    (r'#include\s+"\.\.\/src\/([^"]+)"',           r'#include "\1"'),
]


def rewrite_includes(text):
    for pattern, repl in INCLUDE_REWRITES:
        text = re.sub(pattern, repl, text)
    return text


def copy_file(src_rel, dst_name=None, rewrite=True):
    src_path = os.path.join(REPO_ROOT, src_rel)
    if dst_name is None:
        dst_name = os.path.basename(src_rel)
    dst_path = os.path.join(ARDUINO_SRC, dst_name)

    with open(src_path, "r", encoding="utf-8") as f:
        content = f.read()

    if rewrite:
        content = rewrite_includes(content)

    with open(dst_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"  copied: {src_rel} → extras/arduino/src/{dst_name}")


def make_zip(zip_path):
    """Create a zip of extras/arduino/ with QuartzRTOS/ as the top-level folder.

    Arduino IDE expects the zip to contain exactly one top-level directory whose
    name becomes the installed library name.  We use 'QuartzRTOS' to match the
    'name' field in library.properties.
    """
    lib_name = "QuartzRTOS"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(ARDUINO_ROOT):
            # Skip hidden directories (e.g. .git)
            dirs[:] = [d for d in dirs if not d.startswith(".")]
            for fname in files:
                full_path = os.path.join(root, fname)
                # Build the archive path: QuartzRTOS/<relative path inside extras/arduino/>
                rel = os.path.relpath(full_path, ARDUINO_ROOT)
                arc_name = os.path.join(lib_name, rel)
                zf.write(full_path, arc_name)
    print(f"  created: {zip_path}")
    print(f"  Install: Arduino IDE → Sketch → Include Library → Add .ZIP Library")


def main():
    parser = argparse.ArgumentParser(
        description="Assemble the QuartzRTOS Arduino library from the main source tree."
    )
    parser.add_argument(
        "--zip",
        metavar="PATH",
        nargs="?",
        const=os.path.join(REPO_ROOT, "QuartzRTOS.zip"),
        help="Also produce a .zip for Arduino IDE installation "
             "(default path: QuartzRTOS.zip in the repo root). "
             "Pass a custom path to override.",
    )
    args = parser.parse_args()
    print(f"Packaging Quartz RTOS Arduino library")
    print(f"  repo root : {REPO_ROOT}")
    print(f"  output    : {ARDUINO_SRC}")
    print()

    os.makedirs(ARDUINO_SRC, exist_ok=True)

    print("Copying kernel sources:")
    for src in KERNEL_SOURCES:
        copy_file(src)

    print("\nCopying internal headers:")
    for hdr in INTERNAL_HEADERS:
        copy_file(hdr)

    print("\nCopying public headers:")
    for hdr in PUBLIC_HEADERS:
        copy_file(hdr)

    print("\nCopying port files as .inc:")
    for src, dst in PORT_INC_FILES.items():
        copy_file(src, dst_name=dst)

    print("\nGenerating port.c dispatch file:")
    port_c_path = os.path.join(ARDUINO_SRC, "port.c")
    with open(port_c_path, "w", encoding="utf-8") as f:
        f.write(PORT_C_CONTENT)
    print("  generated: extras/arduino/src/port.c")

    print("\nCopying LICENSE:")
    src_license = os.path.join(REPO_ROOT, "LICENSE")
    dst_license = os.path.join(ARDUINO_ROOT, "LICENSE")
    shutil.copy2(src_license, dst_license)
    print("  copied: LICENSE → extras/arduino/LICENSE")

    print("\nDone. The Arduino library is ready in extras/arduino/")

    if args.zip:
        print(f"\nCreating zip:")
        make_zip(args.zip)
    else:
        print("Tip: run with --zip to also produce QuartzRTOS.zip for direct IDE installation.")


if __name__ == "__main__":
    sys.exit(main())
